### ISSUE TITLE
Unable to connect data servers... Please try again later

### ISSUE THREAD

**Issue by TTT2866** [ofarukcaki/dataleaks#5]
I'm very confused on this. How do I connect 'data servers'? and how do I make an admin account?

I've got a basic PHP server installed :)
Thank you!

**Comment by ofarukcaki** [comment]
Hello @TTT2866,

This error is caused because you didn't add any database or you write the DB credentials wrong.

You can see [here ](https://github.com/ofarukcaki/dataleaks/tree/master/databases)to see example database structures:

And there is no admin account. You need to add databases directly to the your SQL server.

Cheers

**Comment by midnightlovell** [comment]
> Hello @TTT2866,
> 
> This error is caused because you didn't add any database or you write the DB credentials wrong.
> 
> You can see [here ](https://github.com/ofarukcaki/dataleaks/tree/master/databases)to see example database structures:
> 
> And there is no admin account. You need to add databases directly to the your SQL server.
> 
> Cheers

explain what I need to do for Enter necessary database credentials:
I am very new to this and not sure what to change or fill in as the instructions aren't very thorough.
